from tavily import TavilyClient
import pandas as pd
import os

client = TavilyClient("API_KEY")
# q = input(str("What do you want know?: "))

def searchInternet(q):
    try:
        search = client.search(
            query=q,
            include_answer="basic",
            search_depth="advanced"
        )

        answer = search.get("answer", "")
        urls = []

        for result in search.get("results", [])[:3]:
            if "url" in result:
                urls.append(result["url"])

        if answer and urls:
            answer += "- Sources:\n" + "\n".join(f"- {u}" for u in urls)
        elif answer:
            answer += "\n\n(No sources returned in top results)"
        else:
            answer = "No answer generated by Tavily."
        # print(answer)
        
        new_row = pd.DataFrame([{
            "question": q,
            "answer": answer
        }])
        file = "0000.csv"
        if os.path.exists(file):
            new_row.to_csv(file, mode="a", header=False, index=False)
        else:
            print("file does not exist!")
    except Exception as e:
        return f"Error during Tavily search: {str(e)}"
    return answer

# q = input(str("What do you want know?: "))
# searchInternet(q)
    

# print(search["answer"])

# for obj in search['results'][:3]:
#     print("\n")
#     print(obj["url"])
